# Generated by Django 4.2.16 on 2024-04-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmigo_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='MedicineSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(db_index=True, max_length=255)),
                ('normalized_synonym', models.CharField(db_index=True, max_length=255)),
                ('is_brand_name', models.BooleanField(default=False)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='pharmigo_chatbot.medicine')),
            ],
            options={
                'unique_together': {('medicine', 'synonym')},
            },
        ),
    ]