# Generated by Django 4.2.16 on 2026-04-28 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0008_prescription_confidence_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmigo_chatbot', '0002_medicine_synonyms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('keywords', models.TextField(blank=True)),
                ('role_target', models.CharField(choices=[('patient', 'Patient'), ('pharmacy', 'Pharmacy'), ('all', 'All')], db_index=True, default='all', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'question'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotLearningData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('detected_intent', models.CharField(blank=True, max_length=120)),
                ('detected_medicine', models.CharField(blank=True, max_length=255)),
                ('corrected_medicine', models.CharField(blank=True, max_length=255)),
                ('corrected_answer', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('patient', 'Patient'), ('pharmacy', 'Pharmacy'), ('admin', 'Admin'), ('system', 'System')], default='system', max_length=20)),
                ('confidence_before', models.FloatField(default=0.0)),
                ('confidence_after', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_learning_events', to='prescriptions.prescription')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_learning_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
