# Generated by Django 4.2.16 on 2026-05-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmigo_chatbot', '0006_retrievaldocument_retrievalstoreconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmiGoAIEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('gemini_error', 'Gemini error'), ('fallback_used', 'Fallback used'), ('config_change', 'Config change'), ('learning_observation', 'Learning observation')], max_length=40)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'PharmiGo AI event log',
                'verbose_name_plural': 'PharmiGo AI event logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmiGoAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_layer', models.BooleanField(default=True)),
                ('learning_passif', models.BooleanField(default=True)),
                ('fallback_ai', models.BooleanField(default=True)),
                ('memory_engine', models.BooleanField(default=False)),
                ('semantic_search', models.BooleanField(default=False)),
                ('local_reasoning', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PharmiGo AI settings',
                'verbose_name_plural': 'PharmiGo AI settings',
            },
        ),
    ]
