# Generated by Django 4.2.16 on 2026-05-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmigo_chatbot', '0007_pharmigoaieventlog_pharmigoaisettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnedMedicalPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField()),
                ('detected_intent', models.CharField(blank=True, max_length=255)),
                ('medical_context', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('is_validated', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('gemini', 'Gemini'), ('fallback', 'Fallback')], default='gemini', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Learned medical pattern',
                'verbose_name_plural': 'Learned medical patterns',
                'ordering': ['-created_at'],
            },
        ),
    ]
