# Generated by Django 4.2.16 on 2026-04-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_recipient_pharmacy_and_more'),
        ('notifications', '0002_seed_notifications'),
    ]

    operations = [
    ]
