# Generated by Django 4.2.16 on 2026-05-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_birth_date_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_content_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
