# Generated by Django 4.2.16 on 2026-04-28 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0004_merge_0002_pharmacycomment_pharmacyengagement_0003_pharmacy_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacted_by', to='pharmacies.pharmacy')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='pharmacies.pharmacy')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('pharmacy', 'contact_pharmacy')},
            },
        ),
    ]
