# Generated by Django 4.2.16 on 2026-04-28 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacies', '0005_pharmacycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_bif', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('BIF', 'BIF')], default='BIF', max_length=3)),
                ('payment_method', models.CharField(choices=[('lumicash', 'Lumicash'), ('ecocash', 'EcoCash'), ('vodacom_m_pesa', 'Vodacom M-Pesa')], max_length=20)),
                ('sender_phone', models.CharField(max_length=30)),
                ('receiver_phone', models.CharField(max_length=30)),
                ('transaction_reference', models.CharField(max_length=100, unique=True)),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('payment_month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pharmacies.pharmacy')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_start_date', models.DateTimeField(auto_now_add=True)),
                ('trial_end_date', models.DateTimeField()),
                ('is_trial_active', models.BooleanField(default=True)),
                ('subscription_status', models.CharField(choices=[('trial', 'Essai'), ('active', 'Actif'), ('expired', 'Expiré'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé')], default='trial', max_length=20)),
                ('monthly_price_usd', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('current_exchange_rate_bif', models.DecimalField(decimal_places=2, default=2850.0, max_digits=10)),
                ('monthly_price_bif', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('last_payment_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='pharmacies.pharmacy')),
            ],
        ),
    ]
