# Generated by Django 4.2.16 on 2026-05-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0009_pharmacy_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
