# Generated by Django 4.2.16 on 2026-05-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0011_subscriptionpayment_payer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='retail_supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='wholesale_supported',
            field=models.BooleanField(default=False),
        ),
    ]
