# Generated by Django 4.2.16 on 2026-05-11 11:34

import apps.common.public_storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_referral_codes(apps, schema_editor):
    Pharmacy = apps.get_model("pharmacies", "Pharmacy")
    seen_codes = set()
    for pharmacy in Pharmacy.objects.all().order_by("id"):
        base_token = "".join(char for char in (pharmacy.name or "PHARMIGO").upper() if char.isalnum())[:8] or "PHARMIGO"
        seed = f"{base_token}{(pharmacy.phone_number or '')[-4:]}"
        candidate = seed[:24] or f"PHARMIGO{pharmacy.id}"
        suffix = 1
        while candidate in seen_codes:
            suffix += 1
            candidate = f"{seed[:18]}{suffix:02d}"[:24] or f"PHARMIGO{pharmacy.id}{suffix}"
        seen_codes.add(candidate)
        pharmacy.referral_code = candidate
        pharmacy.save(update_fields=["referral_code"])


def cleanup_partial_referral_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP INDEX IF EXISTS pharmacies_pharmacy_referral_code_16059722_like;")
        cursor.execute("DROP INDEX IF EXISTS pharmacies_pharmacy_referral_code_16059722;")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacies', '0013_pharmacy_profile_image_blob_and_more'),
    ]

    operations = [
        migrations.RunPython(cleanup_partial_referral_indexes, migrations.RunPython.noop),
        migrations.CreateModel(
            name='PharmacyReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_payment', 'Attente Paiement'), ('pending_activity', 'Attente Activite'), ('validated', 'Valide'), ('rewarded', 'Recompense accordee'), ('fraud_blocked', 'Bloque fraude')], default='pending_payment', max_length=24)),
                ('payment_validated_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=120)),
                ('validated_activity_count', models.PositiveIntegerField(default=0)),
                ('reward_granted_at', models.DateTimeField(blank=True, null=True)),
                ('fraud_blocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_referrals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='subscriptionsystemsettings',
            name='reward_bonus_days',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='subscriptionsystemsettings',
            name='reward_device_daily_limit',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subscriptionsystemsettings',
            name='reward_event_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionsystemsettings',
            name='reward_event_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionsystemsettings',
            name='reward_instructions',
            field=models.TextField(blank=True, default="Programme ambassadeur PharmiGo\n\n1. Partagez votre lien de parrainage avec une autre pharmacie.\n2. La pharmacie filleule doit soumettre une preuve de paiement validee par l'admin.\n3. Elle doit ensuite traiter au moins 10 ordonnances reelles.\n4. Toute activite repetitive suspecte sur le meme appareil est bloquee et remontee a l'administration.\n5. A partir du seuil de validations configure, PharmiGo ajoute automatiquement des jours gratuits a votre abonnement."),
        ),
        migrations.AddField(
            model_name='subscriptionsystemsettings',
            name='reward_min_activity_count',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='subscriptionsystemsettings',
            name='reward_referral_threshold',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=apps.common.public_storage.PharmigoPublicMediaStorage(), upload_to='pharmacies/'),
        ),
        migrations.AlterField(
            model_name='subscriptionsystemsettings',
            name='trial_period_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='PharmacyReferralFraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_fingerprint', models.CharField(max_length=120)),
                ('repeated_dates', models.JSONField(blank=True, default=list)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('reviewed', 'Examinee')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_fraud_alerts', to='pharmacies.pharmacy')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='pharmacies.pharmacyreferral')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyReferralDeviceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.PositiveIntegerField()),
                ('device_fingerprint', models.CharField(max_length=120)),
                ('source_label', models.CharField(blank=True, default='', max_length=80)),
                ('activity_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_device_logs', to='pharmacies.pharmacy')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_logs', to='pharmacies.pharmacyreferral')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pharmacyreferral',
            name='referee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_referral', to='pharmacies.pharmacy'),
        ),
        migrations.AddField(
            model_name='pharmacyreferral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to='pharmacies.pharmacy'),
        ),
        migrations.RunPython(populate_referral_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pharmacy',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=24, unique=True),
        ),
        migrations.AddConstraint(
            model_name='pharmacyreferraldevicelog',
            constraint=models.UniqueConstraint(fields=('referral', 'prescription_id', 'device_fingerprint', 'activity_date'), name='unique_referral_prescription_device_day'),
        ),
    ]
