# Generated by Django 4.2.16 on 2026-04-23 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_pharmacy_profile_image'),
        ('prescriptions', '0004_prescription_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_engagements', to='pharmacies.pharmacy')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='prescriptionengagement',
            constraint=models.UniqueConstraint(fields=('prescription', 'pharmacy'), name='unique_prescription_engagement'),
        ),
    ]
