# Generated by Django 4.2.16 on 2026-04-23 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_pharmacy_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescriptions', '0005_prescriptionengagement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='prescriptionengagement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_engagements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescriptionengagement',
            name='pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_engagements', to='pharmacies.pharmacy'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionengagement',
            constraint=models.UniqueConstraint(fields=('prescription', 'user'), name='unique_prescription_engagement_user'),
        ),
        migrations.AddField(
            model_name='prescriptioncomment',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='prescriptioncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
