# Generated by Django 4.2.16 on 2026-04-29 21:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0008_prescription_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionAnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('needs_confirmation', 'Needs confirmation'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('raw_ocr_text', models.TextField(blank=True, null=True)),
                ('raw_gemini_text', models.TextField(blank=True, null=True)),
                ('ocr_payload', models.JSONField(blank=True, default=dict)),
                ('gemini_payload', models.JSONField(blank=True, default=dict)),
                ('analysis_payload', models.JSONField(blank=True, default=list)),
                ('global_score', models.FloatField(default=0.0)),
                ('needs_confirmation', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tasks', to='prescriptions.prescription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('message', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_logs', to='prescriptions.prescription')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='prescriptions.prescriptionanalysistask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
