# Generated by Django 4.2.16 on 2026-05-02 10:09

import uuid
from django.db import migrations, models


def backfill_secure_prescription_metadata(apps, schema_editor):
    Prescription = apps.get_model("prescriptions", "Prescription")
    UserProfile = apps.get_model("users", "UserProfile")

    for prescription_id, public_reference, geo_zone, patient_user_id in Prescription.objects.order_by("id").values_list(
        "id",
        "public_reference",
        "geo_zone",
        "patient_user_id",
    ).iterator():
        updates = {}

        if not public_reference or public_reference.startswith("ORD-"):
            updates["public_reference"] = str(uuid.uuid4())

        if not geo_zone:
            address = ""
            if patient_user_id:
                address = str(
                    UserProfile.objects.filter(user_id=patient_user_id).values_list("address", flat=True).first() or ""
                ).strip()
            if address:
                parts = [part.strip() for part in address.split(",") if part.strip()]
                updates["geo_zone"] = (parts[-1] if parts else address)[:120]
            else:
                updates["geo_zone"] = "Zone non renseignee"

        if updates:
            Prescription.objects.filter(id=prescription_id).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0011_prescription_public_reference'),
        ('users', '0003_userprofile_presence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='document_content_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='prescription',
            name='geo_zone',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='prescription',
            name='private_document_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='prescription',
            name='private_document_original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='public_reference',
            field=models.CharField(blank=True, db_index=True, max_length=36, null=True, unique=True),
        ),
        migrations.RunPython(backfill_secure_prescription_metadata, migrations.RunPython.noop),
    ]
