# Generated by Django 4.2.16 on 2026-05-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0012_prescription_document_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacystock',
            name='currency',
            field=models.CharField(choices=[('BIF', 'BIF'), ('FC', 'FC'), ('TSH', 'TSH')], default='BIF', max_length=4),
        ),
    ]
